import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// all Clerk hooks and components must be children of the <ClerkProvider> component, which provides active session and user context
import { ClerkProvider } from "@clerk/nextjs";
// render the 'Toaster' component and display when needed
import { Toaster } from "@/components/ui/toaster";
// wraps your app to provide global functionality to your tooltips
import { TooltipProvider } from "@/components/ui/tooltip";
import QCProvider from "@/components/QCProvider";
import { StateProvider } from "@/components/StateProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root Layout Component wraps around all routes inside the application
// it ensures a consistent layout for all routes within the application
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <QCProvider>
            <StateProvider>
              <TooltipProvider>{children}</TooltipProvider>
            </StateProvider>
          </QCProvider>

          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
